name: code-coverage-lab

# Trigger for master branch only
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-integration-test:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew build -x test
    
    - name: Run tests
      run: ./gradlew test

    - name: Run coverage
      run: ./gradlew jacocoTestReport

    - name: Run codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: e22ef9b9-8cad-4931-a8b7-45ef908e6760
        files: ./jacocoTestReport.xml
        directory: ./build/reports/jacoco/test/
        fail_ci_if_error: true
        verbose: true
